
spring:
    jpa:
        open-in-view: false
        show-sql: true

        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                highlight_sql: true
                auto_quote_keyword: true
#        hibernate:
#          ddl-auto: create

    profiles:
        active: prod
    lifecycle:
        timeout-per-shutdown-phase: 30s
    application:
        name: 3runner-coupon

server:
    shutdown: graceful

logging:
    level:
        org.hibernate.orm.jdbc.bind: trace
        org.springframework.transaction.interceptor: trace
