logging:
  level:
    root: debug

spring:
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-coupon

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true


server:
  shutdown: graceful
  port: 8083