spring:
    config:
        activate:
            on-profile: prod

    datasource:
        url: jdbc:mysql://133.186.241.167:3306/be6_3runner_coupon
        username: be6_3runner
        password: tHos2g5st4@XH7mT
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
            initial-size: 5
            max-total: 20
            max-idle: 20
            min-idle: 5
            test-on-borrow: true
            validation-query: SELECT 1

    rabbitmq:
        host: 133.186.241.167
        port: 5672
        username: admin
        password: nhnacademy123!


eureka:
    client:
        fetch-registry: true
        service-url:
            defaultZone:
                http://admin:1234@eureka:8761/eureka
    instance:
        pref₩er-ip-address: true

feign:
    bookstore:
        url: bookstore:8081